sudo: required
dist: trusty
group: edge

# whitelist
branches:
  only:
    - master

language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

#    - os: linux
#      compiler: gcc
#      addons:
#        apt:
#          sources: ['ubuntu-toolchain-r-test']
#          packages: ['g++-5']
#      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang
            - libiomp-dev
      env:
        - COMPILER=clang
        - CXXFLAGS="-fopenmp=libiomp5"

before_install:
    - sudo apt-get update
    - sudo apt-get install pkg-config autoconf-archive autotools-dev libicu-dev libxml2-dev libbz2-dev zlib1g-dev
    - git clone https://github.com/proycon/ticcutils
    - cd ticcutils
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
    - git clone https://github.com/proycon/libfolia
    - cd libfolia
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
    - git clone https://github.com/proycon/timbl
    - cd timbl
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
    - git clone https://github.com/proycon/timblserver
    - cd timblserver
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
    - git clone https://github.com/proycon/mbt
    - cd mbt
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
    - cd ..
install:
    - bash bootstrap.sh
    - ./configure
    - make CXX=$COMPILER
    - sudo make CXX=$COMPILER install
script:
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib make CXX=$COMPILER check
